name: Build and GH-Page Deploy

on:
  push:
    branches:
      - father

jobs:
  # Build job
  build:
    # <Not provided for brevity>
    # At a minimum this job should upload artifacts using actions/upload-pages-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install dependencies
        uses: actions/setup-node@v2
      - run: npm install

      - name: Build the project
        uses: actions/setup-node@v2
      - run: npm run build

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Init new repo in dist folder and commit generated files
        run: |
          cd dist
          git init
          git add -A
          git config --local user.email "muathye@gmail.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'