name: Build and GH-Page Deploy

on:
  push:
    branches:
      - father

jobs:
  build:
    environment:
      name: develop
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v1
        with:
          branch: gh-pages
          folder: dist
